In [25]:
import pandas as pd
import numpy as np

In [26]:
people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'], 
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, None, 'Missing'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

In [36]:
df = pd.DataFrame(people)

df.replace('NA', np.nan, inplace = True)
df.replace('Missing', np.nan, inplace = True)

In [37]:
df.head(3)

first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [38]:
# Drop N/A Values 

df.dropna()

first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [39]:
# Conditional Drop If ANY Values Missing

df.dropna(axis = 'index', how = 'any')

first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [40]:
# Conditional Drop If ALL Values Missing

df.dropna(axis = 'index', how = 'all')

first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com    33
1   Jane      Doe        JaneDoe@email.com    55
2   John      Doe        JohnDoe@email.com    63
3  Chris  Schafer                     None    36
5   None     None      Anonymous@email.com  None

In [41]:
df.dropna(axis = 'index', how = 'any', subset = ['email'])

first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com    33
1   Jane      Doe        JaneDoe@email.com    55
2   John      Doe        JohnDoe@email.com    63
5   None     None      Anonymous@email.com  None

In [42]:
df.dropna(axis = 'index', how = 'all', subset = ['last', 'email'])

first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com    33
1   Jane      Doe        JaneDoe@email.com    55
2   John      Doe        JohnDoe@email.com    63
3  Chris  Schafer                     None    36
5   None     None      Anonymous@email.com  None

In [46]:
df.head(15)

first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com    33
1   Jane      Doe        JaneDoe@email.com    55
2   John      Doe        JohnDoe@email.com    63
3  Chris  Schafer                     None    36
4    NaN      NaN                      NaN  None
5   None     None      Anonymous@email.com  None
6    NaN      NaN                      NaN   NaN

In [44]:
# Boolean Check of Missing Values 

df.isna()

first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [47]:
# Mask Missing Values 

df.fillna('0')

first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63
3  Chris  Schafer                        0  36
4      0        0                        0   0
5      0        0      Anonymous@email.com   0
6      0        0                        0   0

In [51]:
# Default np.nan Type

type(np.nan)

float

In [52]:
# Convert Int to Str

df['age'] = df['age'].astype(float)

In [54]:
df.dtypes

first     object
last      object
email     object
age      float64
dtype: object

In [56]:
df['age'].mean()

46.75

# Switch to CSV

In [57]:
import pandas as pd

In [59]:
# Creating Default Missing Values 

na_vals = ['NA', 'Missing']

df = pd.read_csv(r'C:\Users\zacha\Hyperborea\csv files\survey_results_public.csv', na_values = na_vals)

In [60]:
df.head(5)

ResponseId                                         MainBranch  \
0           1                     I am a developer by profession   
1           2             I am a student who is learning to code   
2           3  I am not primarily a developer, but I write co...   
3           4                     I am a developer by profession   
4           5                     I am a developer by profession   

                                          Employment  \
0  Independent contractor, freelancer, or self-em...   
1                                 Student, full-time   
2                                 Student, full-time   
3                                 Employed full-time   
4  Independent contractor, freelancer, or self-em...   

                                             Country US_State UK_Country  \
0                                           Slovakia      NaN        NaN   
1                                        Netherlands      NaN        NaN   
2                                 Russian Federation      NaN        NaN   
3                                            Austria      NaN        NaN   
4  United Kingdom of Great Britain and Northern I...      NaN    England   

                                             EdLevel     Age1stCode  \
0  Secondary school (e.g. American high school, G...  18 - 24 years   
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)  11 - 17 years   
2       Bachelor’s degree (B.A., B.S., B.Eng., etc.)  11 - 17 years   
3    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)  11 - 17 years   
4    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   5 - 10 years   

                                           LearnCode YearsCode  ...  \
0  Coding Bootcamp;Other online resources (ex: vi...       NaN  ...   
1  Other online resources (ex: videos, blogs, etc...         7  ...   
2  Other online resources (ex: videos, blogs, etc...       NaN  ...   
3                                                NaN       NaN  ...   
4                            Friend or family member        17  ...   

               Age Gender Trans                Sexuality  \
0  25-34 years old    Man    No  Straight / Heterosexual   
1  18-24 years old    Man    No  Straight / Heterosexual   
2  18-24 years old    Man    No        Prefer not to say   
3  35-44 years old    Man    No  Straight / Heterosexual   
4  25-34 years old    Man    No                      NaN   

                      Ethnicity                Accessibility  \
0  White or of European descent            None of the above   
1  White or of European descent            None of the above   
2             Prefer not to say            None of the above   
3  White or of European descent  I am deaf / hard of hearing   
4  White or of European descent            None of the above   

        MentalHealth           SurveyLength                  SurveyEase  \
0  None of the above  Appropriate in length                        Easy   
1  None of the above  Appropriate in length                        Easy   
2  None of the above  Appropriate in length                        Easy   
3                NaN  Appropriate in length  Neither easy nor difficult   
4                NaN  Appropriate in length                        Easy   

  ConvertedCompYearly  
0             62268.0  
1                 NaN  
2                 NaN  
3                 NaN  
4                 NaN  

[5 rows x 48 columns]

In [61]:
df['YearsCode'].head(10)

0    NaN
1      7
2    NaN
3    NaN
4     17
5    NaN
6      3
7      4
8      6
9      7
Name: YearsCode, dtype: object

In [62]:
df['YearsCode'].mean()

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [64]:
# Convert Str to Float

df['YearsCode'] = df['YearsCode'].astype(float)

ValueError: could not convert string to float: 'Less than 1 year'

In [65]:
# Display All Unique Values 

df['YearsCode'].unique()

array([nan, '7', '17', '3', '4', '6', '16', '12', '15', '10', '40', '9',
       '26', '14', '39', '20', '8', '19', '5', 'Less than 1 year', '22',
       '2', '1', '34', '21', '13', '25', '24', '30', '31', '18', '38',
       'More than 50 years', '27', '41', '42', '35', '23', '28', '11',
       '37', '44', '43', '36', '33', '45', '29', '50', '46', '32', '47',
       '49', '48'], dtype=object)

In [69]:
df['YearsCode'].replace('Less than 1 year', 0, inplace = True)

In [70]:
df['YearsCode'].unique()

array([nan, '7', '17', '3', '4', '6', '16', '12', '15', '10', '40', '9',
       '26', '14', '39', '20', '8', '19', '5', 0, '22', '2', '1', '34',
       '21', '13', '25', '24', '30', '31', '18', '38',
       'More than 50 years', '27', '41', '42', '35', '23', '28', '11',
       '37', '44', '43', '36', '33', '45', '29', '50', '46', '32', '47',
       '49', '48'], dtype=object)

In [71]:
df['YearsCode'].replace('More than 50 years', 0, inplace = True)

In [72]:
df['YearsCode'].unique()

array([nan, '7', '17', '3', '4', '6', '16', '12', '15', '10', '40', '9',
       '26', '14', '39', '20', '8', '19', '5', 0, '22', '2', '1', '34',
       '21', '13', '25', '24', '30', '31', '18', '38', '27', '41', '42',
       '35', '23', '28', '11', '37', '44', '43', '36', '33', '45', '29',
       '50', '46', '32', '47', '49', '48'], dtype=object)

In [73]:
df['YearsCode'] = df['YearsCode'].astype(float)

In [74]:
df['YearsCode'].unique()

array([nan,  7., 17.,  3.,  4.,  6., 16., 12., 15., 10., 40.,  9., 26.,
       14., 39., 20.,  8., 19.,  5.,  0., 22.,  2.,  1., 34., 21., 13.,
       25., 24., 30., 31., 18., 38., 27., 41., 42., 35., 23., 28., 11.,
       37., 44., 43., 36., 33., 45., 29., 50., 46., 32., 47., 49., 48.])

In [75]:
df['YearsCode'].mean()

12.232003527639298

In [76]:
df['YearsCode'].median()

10.0